# Generated by Django 3.0.8 on 2020-08-04 08:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='수량')),
                ('price', models.IntegerField(verbose_name='주문가격')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='주문날짜')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.Item', verbose_name='상품명')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='주문자')),
            ],
        ),
    ]
