# Generated by Django 3.0.8 on 2020-07-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='register_date',
            field=models.DateField(null=True, verbose_name='등록날짜'),
        ),
        migrations.AddField(
            model_name='item',
            name='register_time',
            field=models.TimeField(null=True, verbose_name='등록시간'),
        ),
    ]
