# Generated by Django 2.2.14 on 2020-07-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='view',
            field=models.IntegerField(null=True, verbose_name='조회수'),
        ),
    ]
