# Generated by Django 3.0.8 on 2020-07-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=32, null=True, verbose_name='카테고리'),
        ),
    ]
